/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StepTwoRouteImport } from './routes/step-two'
import { Route as StepThreeRouteImport } from './routes/step-three'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as GameplayRouteImport } from './routes/gameplay'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authenticatedRoutesAuthenticatedRouteImport } from './routes/(authenticated-routes)/_authenticated'
import { Route as authCompleteProfileRouteImport } from './routes/(auth)/complete-profile'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as authenticatedRoutesAuthenticatedResultUnlockRouteImport } from './routes/(authenticated-routes)/_authenticated/result-unlock'
import { Route as authenticatedRoutesAuthenticatedInsightRouteImport } from './routes/(authenticated-routes)/_authenticated/insight'
import { Route as authenticatedRoutesAuthenticatedHelpCenterRouteImport } from './routes/(authenticated-routes)/_authenticated/help-center'
import { Route as authAuthSignInRouteImport } from './routes/(auth)/_auth/sign-in'
import { Route as authAuthGuestSignupRouteImport } from './routes/(auth)/_auth/guest-signup'
import { Route as authenticatedRoutesAuthenticatedProfileIndexRouteImport } from './routes/(authenticated-routes)/_authenticated/profile/index'
import { Route as authenticatedRoutesAuthenticatedProfileWithLoginRouteImport } from './routes/(authenticated-routes)/_authenticated/profile/_with-login'
import { Route as authenticatedRoutesAuthenticatedProfileWithLoginUpdateRouteImport } from './routes/(authenticated-routes)/_authenticated/profile/_with-login/update'
import { Route as authenticatedRoutesAuthenticatedProfileWithLoginSavedResultsRouteImport } from './routes/(authenticated-routes)/_authenticated/profile/_with-login/saved-results'
import { Route as authenticatedRoutesAuthenticatedProfileWithLoginLikedUniversitiesRouteImport } from './routes/(authenticated-routes)/_authenticated/profile/_with-login/liked-universities'

const StepTwoRoute = StepTwoRouteImport.update({
  id: '/step-two',
  path: '/step-two',
  getParentRoute: () => rootRouteImport,
} as any)
const StepThreeRoute = StepThreeRouteImport.update({
  id: '/step-three',
  path: '/step-three',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const GameplayRoute = GameplayRouteImport.update({
  id: '/gameplay',
  path: '/gameplay',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRoutesAuthenticatedRoute =
  authenticatedRoutesAuthenticatedRouteImport.update({
    id: '/(authenticated-routes)/_authenticated',
    getParentRoute: () => rootRouteImport,
  } as any)
const authCompleteProfileRoute = authCompleteProfileRouteImport.update({
  id: '/(auth)/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRoutesAuthenticatedResultUnlockRoute =
  authenticatedRoutesAuthenticatedResultUnlockRouteImport.update({
    id: '/result-unlock',
    path: '/result-unlock',
    getParentRoute: () => authenticatedRoutesAuthenticatedRoute,
  } as any)
const authenticatedRoutesAuthenticatedInsightRoute =
  authenticatedRoutesAuthenticatedInsightRouteImport.update({
    id: '/insight',
    path: '/insight',
    getParentRoute: () => authenticatedRoutesAuthenticatedRoute,
  } as any)
const authenticatedRoutesAuthenticatedHelpCenterRoute =
  authenticatedRoutesAuthenticatedHelpCenterRouteImport.update({
    id: '/help-center',
    path: '/help-center',
    getParentRoute: () => authenticatedRoutesAuthenticatedRoute,
  } as any)
const authAuthSignInRoute = authAuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthGuestSignupRoute = authAuthGuestSignupRouteImport.update({
  id: '/guest-signup',
  path: '/guest-signup',
  getParentRoute: () => authAuthRoute,
} as any)
const authenticatedRoutesAuthenticatedProfileIndexRoute =
  authenticatedRoutesAuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => authenticatedRoutesAuthenticatedRoute,
  } as any)
const authenticatedRoutesAuthenticatedProfileWithLoginRoute =
  authenticatedRoutesAuthenticatedProfileWithLoginRouteImport.update({
    id: '/profile/_with-login',
    path: '/profile',
    getParentRoute: () => authenticatedRoutesAuthenticatedRoute,
  } as any)
const authenticatedRoutesAuthenticatedProfileWithLoginUpdateRoute =
  authenticatedRoutesAuthenticatedProfileWithLoginUpdateRouteImport.update({
    id: '/update',
    path: '/update',
    getParentRoute: () => authenticatedRoutesAuthenticatedProfileWithLoginRoute,
  } as any)
const authenticatedRoutesAuthenticatedProfileWithLoginSavedResultsRoute =
  authenticatedRoutesAuthenticatedProfileWithLoginSavedResultsRouteImport.update(
    {
      id: '/saved-results',
      path: '/saved-results',
      getParentRoute: () =>
        authenticatedRoutesAuthenticatedProfileWithLoginRoute,
    } as any,
  )
const authenticatedRoutesAuthenticatedProfileWithLoginLikedUniversitiesRoute =
  authenticatedRoutesAuthenticatedProfileWithLoginLikedUniversitiesRouteImport.update(
    {
      id: '/liked-universities',
      path: '/liked-universities',
      getParentRoute: () =>
        authenticatedRoutesAuthenticatedProfileWithLoginRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gameplay': typeof GameplayRoute
  '/how-to-play': typeof HowToPlayRoute
  '/step-three': typeof StepThreeRoute
  '/step-two': typeof StepTwoRoute
  '/complete-profile': typeof authCompleteProfileRoute
  '/guest-signup': typeof authAuthGuestSignupRoute
  '/sign-in': typeof authAuthSignInRoute
  '/help-center': typeof authenticatedRoutesAuthenticatedHelpCenterRoute
  '/insight': typeof authenticatedRoutesAuthenticatedInsightRoute
  '/result-unlock': typeof authenticatedRoutesAuthenticatedResultUnlockRoute
  '/profile': typeof authenticatedRoutesAuthenticatedProfileWithLoginRouteWithChildren
  '/profile/': typeof authenticatedRoutesAuthenticatedProfileIndexRoute
  '/profile/liked-universities': typeof authenticatedRoutesAuthenticatedProfileWithLoginLikedUniversitiesRoute
  '/profile/saved-results': typeof authenticatedRoutesAuthenticatedProfileWithLoginSavedResultsRoute
  '/profile/update': typeof authenticatedRoutesAuthenticatedProfileWithLoginUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gameplay': typeof GameplayRoute
  '/how-to-play': typeof HowToPlayRoute
  '/step-three': typeof StepThreeRoute
  '/step-two': typeof StepTwoRoute
  '/complete-profile': typeof authCompleteProfileRoute
  '/guest-signup': typeof authAuthGuestSignupRoute
  '/sign-in': typeof authAuthSignInRoute
  '/help-center': typeof authenticatedRoutesAuthenticatedHelpCenterRoute
  '/insight': typeof authenticatedRoutesAuthenticatedInsightRoute
  '/result-unlock': typeof authenticatedRoutesAuthenticatedResultUnlockRoute
  '/profile': typeof authenticatedRoutesAuthenticatedProfileIndexRoute
  '/profile/liked-universities': typeof authenticatedRoutesAuthenticatedProfileWithLoginLikedUniversitiesRoute
  '/profile/saved-results': typeof authenticatedRoutesAuthenticatedProfileWithLoginSavedResultsRoute
  '/profile/update': typeof authenticatedRoutesAuthenticatedProfileWithLoginUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gameplay': typeof GameplayRoute
  '/how-to-play': typeof HowToPlayRoute
  '/step-three': typeof StepThreeRoute
  '/step-two': typeof StepTwoRoute
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(auth)/complete-profile': typeof authCompleteProfileRoute
  '/(authenticated-routes)/_authenticated': typeof authenticatedRoutesAuthenticatedRouteWithChildren
  '/(auth)/_auth/guest-signup': typeof authAuthGuestSignupRoute
  '/(auth)/_auth/sign-in': typeof authAuthSignInRoute
  '/(authenticated-routes)/_authenticated/help-center': typeof authenticatedRoutesAuthenticatedHelpCenterRoute
  '/(authenticated-routes)/_authenticated/insight': typeof authenticatedRoutesAuthenticatedInsightRoute
  '/(authenticated-routes)/_authenticated/result-unlock': typeof authenticatedRoutesAuthenticatedResultUnlockRoute
  '/(authenticated-routes)/_authenticated/profile/_with-login': typeof authenticatedRoutesAuthenticatedProfileWithLoginRouteWithChildren
  '/(authenticated-routes)/_authenticated/profile/': typeof authenticatedRoutesAuthenticatedProfileIndexRoute
  '/(authenticated-routes)/_authenticated/profile/_with-login/liked-universities': typeof authenticatedRoutesAuthenticatedProfileWithLoginLikedUniversitiesRoute
  '/(authenticated-routes)/_authenticated/profile/_with-login/saved-results': typeof authenticatedRoutesAuthenticatedProfileWithLoginSavedResultsRoute
  '/(authenticated-routes)/_authenticated/profile/_with-login/update': typeof authenticatedRoutesAuthenticatedProfileWithLoginUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/gameplay'
    | '/how-to-play'
    | '/step-three'
    | '/step-two'
    | '/complete-profile'
    | '/guest-signup'
    | '/sign-in'
    | '/help-center'
    | '/insight'
    | '/result-unlock'
    | '/profile'
    | '/profile/'
    | '/profile/liked-universities'
    | '/profile/saved-results'
    | '/profile/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/gameplay'
    | '/how-to-play'
    | '/step-three'
    | '/step-two'
    | '/complete-profile'
    | '/guest-signup'
    | '/sign-in'
    | '/help-center'
    | '/insight'
    | '/result-unlock'
    | '/profile'
    | '/profile/liked-universities'
    | '/profile/saved-results'
    | '/profile/update'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/gameplay'
    | '/how-to-play'
    | '/step-three'
    | '/step-two'
    | '/(auth)/_auth'
    | '/(auth)/complete-profile'
    | '/(authenticated-routes)/_authenticated'
    | '/(auth)/_auth/guest-signup'
    | '/(auth)/_auth/sign-in'
    | '/(authenticated-routes)/_authenticated/help-center'
    | '/(authenticated-routes)/_authenticated/insight'
    | '/(authenticated-routes)/_authenticated/result-unlock'
    | '/(authenticated-routes)/_authenticated/profile/_with-login'
    | '/(authenticated-routes)/_authenticated/profile/'
    | '/(authenticated-routes)/_authenticated/profile/_with-login/liked-universities'
    | '/(authenticated-routes)/_authenticated/profile/_with-login/saved-results'
    | '/(authenticated-routes)/_authenticated/profile/_with-login/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GameplayRoute: typeof GameplayRoute
  HowToPlayRoute: typeof HowToPlayRoute
  StepThreeRoute: typeof StepThreeRoute
  StepTwoRoute: typeof StepTwoRoute
  authAuthRoute: typeof authAuthRouteWithChildren
  authCompleteProfileRoute: typeof authCompleteProfileRoute
  authenticatedRoutesAuthenticatedRoute: typeof authenticatedRoutesAuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/step-two': {
      id: '/step-two'
      path: '/step-two'
      fullPath: '/step-two'
      preLoaderRoute: typeof StepTwoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step-three': {
      id: '/step-three'
      path: '/step-three'
      fullPath: '/step-three'
      preLoaderRoute: typeof StepThreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gameplay': {
      id: '/gameplay'
      path: '/gameplay'
      fullPath: '/gameplay'
      preLoaderRoute: typeof GameplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated-routes)/_authenticated': {
      id: '/(authenticated-routes)/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRoutesAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/complete-profile': {
      id: '/(auth)/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof authCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated-routes)/_authenticated/result-unlock': {
      id: '/(authenticated-routes)/_authenticated/result-unlock'
      path: '/result-unlock'
      fullPath: '/result-unlock'
      preLoaderRoute: typeof authenticatedRoutesAuthenticatedResultUnlockRouteImport
      parentRoute: typeof authenticatedRoutesAuthenticatedRoute
    }
    '/(authenticated-routes)/_authenticated/insight': {
      id: '/(authenticated-routes)/_authenticated/insight'
      path: '/insight'
      fullPath: '/insight'
      preLoaderRoute: typeof authenticatedRoutesAuthenticatedInsightRouteImport
      parentRoute: typeof authenticatedRoutesAuthenticatedRoute
    }
    '/(authenticated-routes)/_authenticated/help-center': {
      id: '/(authenticated-routes)/_authenticated/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof authenticatedRoutesAuthenticatedHelpCenterRouteImport
      parentRoute: typeof authenticatedRoutesAuthenticatedRoute
    }
    '/(auth)/_auth/sign-in': {
      id: '/(auth)/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authAuthSignInRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/guest-signup': {
      id: '/(auth)/_auth/guest-signup'
      path: '/guest-signup'
      fullPath: '/guest-signup'
      preLoaderRoute: typeof authAuthGuestSignupRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(authenticated-routes)/_authenticated/profile/': {
      id: '/(authenticated-routes)/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof authenticatedRoutesAuthenticatedProfileIndexRouteImport
      parentRoute: typeof authenticatedRoutesAuthenticatedRoute
    }
    '/(authenticated-routes)/_authenticated/profile/_with-login': {
      id: '/(authenticated-routes)/_authenticated/profile/_with-login'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authenticatedRoutesAuthenticatedProfileWithLoginRouteImport
      parentRoute: typeof authenticatedRoutesAuthenticatedRoute
    }
    '/(authenticated-routes)/_authenticated/profile/_with-login/update': {
      id: '/(authenticated-routes)/_authenticated/profile/_with-login/update'
      path: '/update'
      fullPath: '/profile/update'
      preLoaderRoute: typeof authenticatedRoutesAuthenticatedProfileWithLoginUpdateRouteImport
      parentRoute: typeof authenticatedRoutesAuthenticatedProfileWithLoginRoute
    }
    '/(authenticated-routes)/_authenticated/profile/_with-login/saved-results': {
      id: '/(authenticated-routes)/_authenticated/profile/_with-login/saved-results'
      path: '/saved-results'
      fullPath: '/profile/saved-results'
      preLoaderRoute: typeof authenticatedRoutesAuthenticatedProfileWithLoginSavedResultsRouteImport
      parentRoute: typeof authenticatedRoutesAuthenticatedProfileWithLoginRoute
    }
    '/(authenticated-routes)/_authenticated/profile/_with-login/liked-universities': {
      id: '/(authenticated-routes)/_authenticated/profile/_with-login/liked-universities'
      path: '/liked-universities'
      fullPath: '/profile/liked-universities'
      preLoaderRoute: typeof authenticatedRoutesAuthenticatedProfileWithLoginLikedUniversitiesRouteImport
      parentRoute: typeof authenticatedRoutesAuthenticatedProfileWithLoginRoute
    }
  }
}

interface authAuthRouteChildren {
  authAuthGuestSignupRoute: typeof authAuthGuestSignupRoute
  authAuthSignInRoute: typeof authAuthSignInRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthGuestSignupRoute: authAuthGuestSignupRoute,
  authAuthSignInRoute: authAuthSignInRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface authenticatedRoutesAuthenticatedProfileWithLoginRouteChildren {
  authenticatedRoutesAuthenticatedProfileWithLoginLikedUniversitiesRoute: typeof authenticatedRoutesAuthenticatedProfileWithLoginLikedUniversitiesRoute
  authenticatedRoutesAuthenticatedProfileWithLoginSavedResultsRoute: typeof authenticatedRoutesAuthenticatedProfileWithLoginSavedResultsRoute
  authenticatedRoutesAuthenticatedProfileWithLoginUpdateRoute: typeof authenticatedRoutesAuthenticatedProfileWithLoginUpdateRoute
}

const authenticatedRoutesAuthenticatedProfileWithLoginRouteChildren: authenticatedRoutesAuthenticatedProfileWithLoginRouteChildren =
  {
    authenticatedRoutesAuthenticatedProfileWithLoginLikedUniversitiesRoute:
      authenticatedRoutesAuthenticatedProfileWithLoginLikedUniversitiesRoute,
    authenticatedRoutesAuthenticatedProfileWithLoginSavedResultsRoute:
      authenticatedRoutesAuthenticatedProfileWithLoginSavedResultsRoute,
    authenticatedRoutesAuthenticatedProfileWithLoginUpdateRoute:
      authenticatedRoutesAuthenticatedProfileWithLoginUpdateRoute,
  }

const authenticatedRoutesAuthenticatedProfileWithLoginRouteWithChildren =
  authenticatedRoutesAuthenticatedProfileWithLoginRoute._addFileChildren(
    authenticatedRoutesAuthenticatedProfileWithLoginRouteChildren,
  )

interface authenticatedRoutesAuthenticatedRouteChildren {
  authenticatedRoutesAuthenticatedHelpCenterRoute: typeof authenticatedRoutesAuthenticatedHelpCenterRoute
  authenticatedRoutesAuthenticatedInsightRoute: typeof authenticatedRoutesAuthenticatedInsightRoute
  authenticatedRoutesAuthenticatedResultUnlockRoute: typeof authenticatedRoutesAuthenticatedResultUnlockRoute
  authenticatedRoutesAuthenticatedProfileWithLoginRoute: typeof authenticatedRoutesAuthenticatedProfileWithLoginRouteWithChildren
  authenticatedRoutesAuthenticatedProfileIndexRoute: typeof authenticatedRoutesAuthenticatedProfileIndexRoute
}

const authenticatedRoutesAuthenticatedRouteChildren: authenticatedRoutesAuthenticatedRouteChildren =
  {
    authenticatedRoutesAuthenticatedHelpCenterRoute:
      authenticatedRoutesAuthenticatedHelpCenterRoute,
    authenticatedRoutesAuthenticatedInsightRoute:
      authenticatedRoutesAuthenticatedInsightRoute,
    authenticatedRoutesAuthenticatedResultUnlockRoute:
      authenticatedRoutesAuthenticatedResultUnlockRoute,
    authenticatedRoutesAuthenticatedProfileWithLoginRoute:
      authenticatedRoutesAuthenticatedProfileWithLoginRouteWithChildren,
    authenticatedRoutesAuthenticatedProfileIndexRoute:
      authenticatedRoutesAuthenticatedProfileIndexRoute,
  }

const authenticatedRoutesAuthenticatedRouteWithChildren =
  authenticatedRoutesAuthenticatedRoute._addFileChildren(
    authenticatedRoutesAuthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GameplayRoute: GameplayRoute,
  HowToPlayRoute: HowToPlayRoute,
  StepThreeRoute: StepThreeRoute,
  StepTwoRoute: StepTwoRoute,
  authAuthRoute: authAuthRouteWithChildren,
  authCompleteProfileRoute: authCompleteProfileRoute,
  authenticatedRoutesAuthenticatedRoute:
    authenticatedRoutesAuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
